spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/INF335
    username: root
    password: INF325
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8090
